apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;

        location = /health {
            access_log off;
            add_header 'Content-Type' 'text/plain';
            return 200 'OK';
        }

        {{- range .Values.files }}
        location = {{ .location }} {
            alias /var/static/{{ .name }}/{{ .name }};
        }
        {{- end }}

        server_tokens off;
    }

---
