apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sftpgo.fullname" . }}-db
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.pvc.db.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.pvc.db.storageRequest }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "sftpgo.fullname" . }}-files
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.pvc.files.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.pvc.files.storageRequest }}

