apiVersion: v1
kind: Service
metadata:
  name: {{ include "sftpgo.fullname" . }}-server
  labels:
    {{- include "sftpgo.labelsServer" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    - port: 2022
      targetPort: 2022
      protocol: TCP
      name: sftp
  selector:
    {{- include "sftpgo.selectorLabelsServer" . | nindent 4 }}
---
