apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kanidm.fullname" . }}-config
  labels:
    {{- include "kanidm.labels" . | nindent 4 }}
data:
  server.toml: |
    version = "2"
    bindaddress = "0.0.0.0:8443"
    db_path = "/db/kanidm.db"
    tls_chain = "/certs/tls.crt"
    tls_key = "/certs/tls.key"
    domain = "{{ .Values.config.domain }}"
    origin = "{{ .Values.config.origin }}"
    [online_backup]
    path = "/data/backups/"
    schedule = "00 22 * * *"
    versions = 1

