apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kanidm.fullname" . }}-config
  labels:
    {{- include "kanidm.labels" . | nindent 4 }}
data:
  server.toml: |
    bindaddress = "0.0.0.0:8443"
    db_path = "/data/kanidm.db"
    tls_chain = "/certs/tls.crt"
    tls_key = "/certs/tls.key"
    domain = "{{ .Values.config.domain }}"
    origin = "{{ .Values.config.origin }}"
    {{- if .Values.config.trustForwardHeader }}
    trust_x_forward_for = "{{ .Values.config.trustForwardHeader }}"
    {{- end }}

