apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kanidm.fullname" . }}-db
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.pvc.db.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.pvc.db.storageRequest }}

