apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "gh-kopia-backup.fullname" . }}-runner
  labels:
    {{- include "gh-kopia-backup.labelsRunner" . | nindent 4 }}
spec:
  schedule: "{{ .Values.schedule }}"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: runner
              image: "ghcr.io/bradenrayhorn/gh-kopia-backup:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
                - name: GITHUB_USERNAME
                  value: {{ .Values.github_username }}
                - name: GITHUB_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: gh-kopia-backup-secret-config
                      key: github-token
                - name: KOPIA_CONFIG
                  valueFrom:
                    secretKeyRef:
                      name: gh-kopia-backup-secret-config
                      key: kopia-config
---
