apiVersion: v1
kind: Service
metadata:
  name: {{ include "nunc.fullname" . }}-server
  labels:
    {{- include "nunc.labelsServer" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    {{- include "nunc.selectorLabelsServer" . | nindent 4 }}
---
