apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "nunc.fullname" . }}-server
  labels:
    {{- include "nunc.labelsServer" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "nunc.selectorLabelsServer" . | nindent 6 }}
  serviceName: {{ include "nunc.fullname" . }}-server
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nunc.selectorLabelsServer" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "nunc.serviceAccountName" . }}
      containers:
        - name: nunc-server
          image: "ghcr.io/bradenrayhorn/nunc:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
---
