apiVersion: v1
kind: Service
metadata:
  name: {{ include "sproochen.fullname" . }}-app
  labels:
    {{- include "sproochen.labelsApp" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "sproochen.selectorLabelsApp" . | nindent 4 }}
---
