apiVersion: v1
kind: Service
metadata:
  name: {{ include "sproochen.fullname" . }}-server
  labels:
    {{- include "sproochen.labelsServer" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "sproochen.selectorLabelsServer" . | nindent 4 }}
---
