apiVersion: v1
kind: Service
metadata:
  name: {{ include "actualbudget.fullname" . }}-server
  labels:
    {{- include "actualbudget.labelsServer" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5006
      targetPort: 5006
      protocol: TCP
      name: http
  selector:
    {{- include "actualbudget.selectorLabelsServer" . | nindent 4 }}
---
