apiVersion: v1
kind: Service
metadata:
  name: {{ include "mise.fullname" . }}-server
  labels:
    {{- include "mise.labelsServer" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "mise.selectorLabelsServer" . | nindent 4 }}
---
