apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "webapp.fullname" . }}
  labels:
{{ include "webapp.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "webapp.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "webapp.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    {{- if .Values.container.annotations }}
      annotations:
        {{- toYaml .Values.container.annotations | nindent 8 }}
    {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "webapp.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
    {{- if .Values.container.restartPolicy }}
      restartPolicy: {{ .Values.container.restartPolicy }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          {{- range .Values.container.ports }}
            - containerPort: {{ . }}
          {{- end }}
          {{- if .Values.container.env }}
          env:
            {{- toYaml .Values.container.env | nindent 12 }}
          {{- end }}
          {{- if .Values.container.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.container.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.container.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.container.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- if .Values.volumes }}
          volumeMounts:
          {{- range .Values.volumes }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
          {{- end }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.volumes }}
      volumes:
      {{- range . }}
        - name: {{ .name }}
          persistentVolumeClaim:
            claimName: {{ include "webapp.fullname" $ }}-{{ .pvc }}
      {{- end }}
    {{- end }}
