{{- range .Values.jobs }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "webapp.fullname" $ }}-{{ .name }}
  labels:
{{ include "webapp.labels" $ | indent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      name: {{ include "webapp.fullname" $ }}-{{ .name  }}
      labels:
{{ include "webapp.labels" $ | indent 8 }}
    {{- if .annotations }}
      annotations:
        {{- toYaml .annotations | nindent 8 }}
    {{- end }}
    spec:
      restartPolicy: Never
      serviceAccountName: {{ template "webapp.serviceAccountName" $ }}
      {{- with .containers }}
      containers:
        {{- toYaml . | nindent 6 }}
      {{- end }}
---
{{- end }}

