{{- range .Values.pvc }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}
spec:
  accessModes:
    - {{ .accessMode }}
  storageClassName: {{ .storageClassName }}
  resources:
    requests:
      storage: {{ .storageRequest }}
---
{{- end }}

