apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "uptimekuma.fullname" . }}-server
  labels:
    {{- include "uptimekuma.labelsServer" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "uptimekuma.selectorLabelsServer" . | nindent 6 }}
  serviceName: {{ include "uptimekuma.fullname" . }}-server
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "uptimekuma.selectorLabelsServer" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "uptimekuma.serviceAccountName" . }}
      volumes:
        - name: app-data
          persistentVolumeClaim:
            claimName: {{ include "uptimekuma.fullname" . }}-data
      containers:
        - name: uptimekuma-server
          image: "docker.io/louislam/uptime-kuma:1"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: app-data
              mountPath: /app/data/
          ports:
            - name: http
              containerPort: 3001
              protocol: TCP
          livenessProbe:
            exec:
              command:
                - extra/healthcheck
          readinessProbe:
            httpGet:
              path: /
              port: 3001
          resources:
            {{- toYaml .Values.resources.server | nindent 12 }}
---
